profile_name: default # This name should match the 'profile' key in your dbt_project.yml
target: dev
outputs:
  dev:
    type: snowflake
    account: SFSEHOL-MEDTRONICS_SNOW_CAMP_2025_LSHMCI # e.g., ab12345.us-east-1.aws
    user: user
    password: sn0wf@ll
    # done by Jitendra
    role: ATTENDEE_ROLE # e.g., DBT_ROLE
    database: DEV_SDH_DB # e.g., DBT_DB
    warehouse: DEFAULT_WH # e.g., DBT_WH
    schema: ARIBA # e.g., DBT_SCHEMA
    threads: 4 # Number of concurrent threads for dbt operations (typically 1-8)
    client_session_keep_alive: false # Optional: Set to true for long-running sessions
    query_tag: dbt_project_tag # Optional: A tag to identify queries from this dbt project
